### ISSUE TITLE
Phiên bản 1.12 ?

### ISSUE THREAD

**Issue by Thaijoy279** [thuan782004/Gilded_Upgrade#1]
Mong anh có thể cho dùng ở phiên bản 1.12, đây là một plugin rất hay!

**Comment by thuan782004** [comment]
### Đã hỗ trợ
Đây là một bản hỗ trợ nhanh
sắp tới mình sẽ hỗ trợ và test lỗi kỹ trên các phiên bản từ 1.8 đến phiên bản mới nhất
