### ISSUE TITLE
More support versions !

### ISSUE THREAD

**Issue by thuan782004** [thuan782004/Gilded_Upgrade#2]
Mình đang trong quá trình thiết lập hỗ trợ từ 1.8 đến 1.17.1!
Cảm ơn vì đã ủng hộ. <3

**Comment by letrongphuoc** [comment]
Vui lòng xem lại câu lệnh [ /gu generator ], nó đã xảy ra lỗi.

![image](https://user-images.githubusercontent.com/78432940/133892578-5d396908-8ac7-40b8-ba3b-f75b27826489.png)

**Comment by thuan782004** [comment]
> Vui lòng xem lại câu lệnh [ /gu generator ], nó đã xảy ra lỗi.
> 

Lần sau vui lòng tạo một chủ đề mới hoặc nhắn qua discord để mình có thể dễ dàng nhìn thấy
lỗi này gây ra do bạn nhập thiếu thông tin
mình đã thêm tin nhắn nhắc nhở cho lệnh này trong phiên bản mới nhất


[discord](https://discord.gg/2VAK8Dmz)
